env:
  browser: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
installedESLint: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  strict: 0
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-uses-react:
    - error
  react/jsx-uses-vars:
    - error

