export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const SUBMIT_CATEGORY_SUCCESS = 'SUBMIT_CATEGORY_SUCCESS';
export const SUBMIT_CATEGORY_FAILURE = 'SUBMIT_CATEGORY_FAILURE';

export const SET_IS_FETCHING_CATEGORIES = 'SET_IS_FETCHING_CATEGORIES';
export const SET_IS_SAVING_CATEGORY = 'SET_IS_SAVING_CATEGORY';
