export const CREATE_EVENT_FAVORITE_SUCCESS = 'CREATE_EVENT_FAVORITE_SUCCESS';
export const CREATE_EVENT_FAVORITE_FAILURE = 'CREATE_EVENT_FAVORITE_FAILURE';
export const SET_IS_SAVING_EVENT_FAVORITES = 'SET_IS_SAVING_EVENT_FAVORITES';

export const SET_IS_DELETING_EVENT_FAVORITE = 'SET_IS_DELETING_EVENT_FAVORITE';
export const DELETE_EVENT_FAVORITE_SUCCESS = 'DELETE_EVENT_FAVORITE_SUCCESS';
export const DELETE_EVENT_FAVORITE_FAILURE = 'DELETE_EVENT_FAVORITE_FAILURE';
export const CLEAR_DELETE_EVENT_FAVORITE_FAILURE = 'CLEAR_DELETE_EVENT_FAVORITE_FAILURE';
