export const CREATE_EVENT_FAVORITE_SUCCESS = 'CREATE_EVENT_FAVORITE_SUCCESS';
export const CREATE_EVENT_FAVORITE_FAILURE = 'CREATE_EVENT_FAVORITE_FAILURE';
export const SET_IS_SAVING_EVENT_FAVORITES = 'SET_IS_SAVING_EVENT_FAVORITES';
