export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';

export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const SAVE_EVENT_SUCCESS = 'SAVE_EVENT_SUCCESS';
export const SAVE_EVENT_FAILURE = 'SAVE_EVENT_FAILURE';
export const CLEAR_SAVE_EVENT_FAILURE = 'CLEAR_SAVE_EVENT_FAILURE';

export const SET_IS_FETCHING_EVENT = 'SET_IS_FETCHING_EVENT';
export const SET_IS_SAVING_EVENT = 'SET_IS_SAVING_EVENT';

export const SET_IS_FETCHING_EVENTS = 'SET_IS_FETCHING_EVENTS';
export const SET_IS_SAVING_EVENTS = 'SET_IS_SAVING_EVENTS';

export const HIDE_EVENT_SAVED_NOTICE = 'HIDE_SAVED_NOTICE';

export const SET_IS_DELETING_EVENT = 'SET_IS_DELETING_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';
export const CLEAR_DELETE_EVENT_FAILURE = 'CLEAR_DELETE_EVENT_FAILURE';
