export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';

export const SUBMIT_TOPIC_SUCCESS = 'SUBMIT_TOPIC_SUCCESS';
export const SUBMIT_TOPIC_FAILURE = 'SUBMIT_TOPIC_FAILURE';

export const SET_IS_FETCHING_CATEGORIES = 'SET_IS_FETCHING_CATEGORIES';
export const SET_IS_SAVING_CATEGORIES = 'SET_IS_SAVING_CATEGORIES';
