export const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS';
export const FETCH_TOPIC_FAILURE = 'FETCH_TOPIC_FAILURE';

export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';

export const SUBMIT_TOPIC_SUCCESS = 'SUBMIT_TOPIC_SUCCESS';
export const SUBMIT_TOPIC_FAILURE = 'SUBMIT_TOPIC_FAILURE';

export const SET_IS_FETCHING_TOPIC = 'SET_IS_FETCHING_TOPIC';

export const SET_IS_FETCHING_TOPICS = 'SET_IS_FETCHING_TOPICS';
export const SET_IS_SAVING_TOPICS = 'SET_IS_SAVING_TOPICS';
