export const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS';
export const FETCH_TOPIC_FAILURE = 'FETCH_TOPIC_FAILURE';

export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';

export const SAVE_TOPIC_SUCCESS = 'SAVE_TOPIC_SUCCESS';
export const SAVE_TOPIC_FAILURE = 'SAVE_TOPIC_FAILURE';
export const CLEAR_SAVE_TOPIC_FAILURE = 'CLEAR_SAVE_TOPIC_FAILURE';

export const SET_IS_FETCHING_TOPIC = 'SET_IS_FETCHING_TOPIC';
export const SET_IS_SAVING_TOPIC = 'SET_IS_SAVING_TOPIC';

export const SET_IS_FETCHING_TOPICS = 'SET_IS_FETCHING_TOPICS';
export const SET_IS_SAVING_TOPICS = 'SET_IS_SAVING_TOPICS';

export const HIDE_TOPIC_SAVED_NOTICE = 'HIDE_SAVED_NOTICE';

export const SET_IS_DELETING_TOPIC = 'SET_IS_DELETING_TOPIC';
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
export const DELETE_TOPIC_FAILURE = 'DELETE_TOPIC_FAILURE';
export const CLEAR_DELETE_TOPIC_FAILURE = 'CLEAR_DELETE_TOPIC_FAILURE';

