// Sign Up
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const CLEAR_SIGN_UP_FAILURE = 'CLEAR_SIGN_UP_FAILURE';
export const SET_IS_SIGNING_UP = 'SET_IS_SIGNING_UP';

// Sign In
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const CLEAR_SIGN_IN_FAILURE = 'CLEAR_SIGN_IN_FAILURE';
export const SET_IS_SIGNING_IN = 'SET_IS_SIGNING_IN';
